import React from 'react'
import { Container, Row, Col } from 'react-bootstrap'

const About = () => {
  return (
    <>
    <Container style={{marginTop:'50px'}}>
        <h1>Qui sommes-nous</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est sit maiores, sed ab autem nam necessitatibus repudiandae perspiciatis? Possimus sint quas repellat, neque porro inventore! Laudantium optio accusamus odit id repellat, quisquam voluptatibus voluptatum esse sapiente nihil vel aliquid. Ullam placeat modi voluptas exercitationem doloremque consequuntur reiciendis ex odit repudiandae. Laudantium ex iste totam voluptatum molestias aspernatur reiciendis repellat iusto tempora animi hic repellendus minus est illum officiis vel accusantium eaque, quod adipisci quibusdam, dolor enim expedita ipsum? Dignissimos aliquid iste velit voluptates. Animi aliquam cum inventore maxime ipsum vitae quaerat esse repellendus molestiae, qui, nostrum ea voluptatem. Dolore, nisi! Amet esse aperiam quidem nihil blanditiis dolorem alias fugiat, asperiores, magnam nemo quam autem vitae tenetur modi molestiae beatae! Enim, consequatur. Impedit obcaecati, commodi voluptate nobis aspernatur illo vitae? Debitis odio impedit fugiat minus, consequuntur necessitatibus ipsum eligendi qui doloremque et. Omnis maxime tenetur, nihil velit earum accusamus repellat consequuntur, cum harum architecto aspernatur corrupti natus minus quasi deleniti in aperiam ad enim numquam non facere illo. Quisquam nemo, veritatis ut iusto amet accusamus, velit, eaque deserunt qui facilis ipsum eveniet consequatur. Natus iusto aliquid eaque aut impedit voluptatem suscipit fuga reprehenderit veritatis. Error minus earum numquam nobis, quos quidem?</p>
        <h1>Notre specialite</h1>
        
        <Row>
            <col md={6}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur dignissimos accusamus autem adipisci incidunt molestias ullam praesentium perspiciatis temporibus corrupti necessitatibus repudiandae dolore doloribus, dolor numquam fugit odit quae voluptatibus. Enim veritatis rem iste repellendus voluptas quisquam non deserunt dolor mollitia quaerat fugiat numquam nihil eum suscipit cupiditate, consectetur cum sapiente aliquam aliquid. Error consequatur quia modi similique aut maiores architecto ducimus reiciendis dolorum amet ipsam corporis facilis aliquid maxime eum voluptatibus, rem officia laborum atque numquam sint animi. Tempora tenetur aut dicta commodi? Minima illum pariatur iure, beatae maiores libero itaque reprehenderit ea enim optio, laborum consectetur suscipit saepe velit quos facilis voluptate aperiam deleniti recusandae repellendus esse! Amet aspernatur doloribus iste, neque accusantium ipsam voluptatum ipsum, cupiditate, necessitatibus a minus quos. Saepe id nostrum voluptas, adipisci deleniti esse quas molestias libero earum nemo nobis tenetur magnam harum laboriosam facilis atque dolorem nesciunt quibusdam explicabo quia natus necessitatibus blanditiis voluptate ad. Corrupti architecto animi ducimus dolorem aliquid, cumque omnis similique blanditiis odio voluptatem ab aliquam voluptatibus iste, nihil quisquam error qui molestiae quas magni beatae velit deserunt asperiores, expedita ullam. Ex, harum quibusdam culpa commodi rerum expedita perferendis at vero! Numquam mollitia adipisci a fuga dolores eum odio. Obcaecati?</p>
            </col>
            <col md={6}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur dignissimos accusamus autem adipisci incidunt molestias ullam praesentium perspiciatis temporibus corrupti necessitatibus repudiandae dolore doloribus, dolor numquam fugit odit quae voluptatibus. Enim veritatis rem iste repellendus voluptas quisquam non deserunt dolor mollitia quaerat fugiat numquam nihil eum suscipit cupiditate, consectetur cum sapiente aliquam aliquid. Error consequatur quia modi similique aut maiores architecto ducimus reiciendis dolorum amet ipsam corporis facilis aliquid maxime eum voluptatibus, rem officia laborum atque numquam sint animi. Tempora tenetur aut dicta commodi? Minima illum pariatur iure, beatae maiores libero itaque reprehenderit ea enim optio, laborum consectetur suscipit saepe velit quos facilis voluptate aperiam deleniti recusandae repellendus esse! Amet aspernatur doloribus iste, neque accusantium ipsam voluptatum ipsum, cupiditate, necessitatibus a minus quos. Saepe id nostrum voluptas, adipisci deleniti esse quas molestias libero earum nemo nobis tenetur magnam harum laboriosam facilis atque dolorem nesciunt quibusdam explicabo quia natus necessitatibus blanditiis voluptate ad. Corrupti architecto animi ducimus dolorem aliquid, cumque omnis similique blanditiis odio voluptatem ab aliquam voluptatibus iste, nihil quisquam error qui molestiae quas magni beatae velit deserunt asperiores, expedita ullam. Ex, harum quibusdam culpa commodi rerum expedita perferendis at vero! Numquam mollitia adipisci a fuga dolores eum odio. Obcaecati?</p>
            </col>
        </Row>
        <Row>
            <h1>Le Chef</h1>
            <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis quae totam fugit veniam reiciendis voluptas consectetur deserunt neque reprehenderit dolore eum vero dignissimos quos voluptatem, enim quod sunt in voluptate cum nostrum repudiandae voluptatibus. Aspernatur, explicabo aperiam? Repellendus tenetur aperiam debitis, recusandae inventore ullam rem dicta accusantium? Sequi ducimus mollitia necessitatibus earum illo laboriosam ipsum? Aut quia velit temporibus porro maiores libero, soluta totam impedit veniam repellendus! Quod asperiores eos animi ipsam tempore, praesentium quo nisi maxime a nostrum eius dicta, dolorum doloribus optio nesciunt, et sint. Nulla doloribus ullam neque esse, commodi odio provident aperiam vel, dolore tempore inventore!</p>
            </Col>
            <Col md={3}>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid voluptates voluptas corrupti. Deserunt eligendi consequatur accusantium corporis, asperiores a porro aliquam. Odio quisquam laborum neque facere maiores suscipit reprehenderit unde dicta quibusdam! Molestias dolores sit odit similique saepe vero perspiciatis magnam, itaque, reiciendis fuga quaerat nam eius nemo, deleniti voluptas possimus nulla eos. Illo placeat voluptatibus voluptatem nulla. Esse nesciunt atque est ad cumque iste, eius mollitia necessitatibus labore, dolorum expedita voluptate repellendus saepe unde doloremque, similique fuga laboriosam nemo neque. Consequatur saepe sapiente iusto incidunt quos sunt eius consectetur ipsam nemo, ad fuga a enim quaerat ratione ab perspiciatis.</p>
            </Col>
            <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis quae totam fugit veniam reiciendis voluptas consectetur deserunt neque reprehenderit dolore eum vero dignissimos quos voluptatem, enim quod sunt in voluptate cum nostrum repudiandae voluptatibus. Aspernatur, explicabo aperiam? Repellendus tenetur aperiam debitis, recusandae inventore ullam rem dicta accusantium? Sequi ducimus mollitia necessitatibus earum illo laboriosam ipsum? Aut quia velit temporibus porro maiores libero, soluta totam impedit veniam repellendus! Quod asperiores eos animi ipsam tempore, praesentium quo nisi maxime a nostrum eius dicta, dolorum doloribus optio nesciunt, et sint. Nulla doloribus ullam neque esse, commodi odio provident aperiam vel, dolore tempore inventore!</p>
            </Col>
        </Row>
    </Container>
    </>
  )
}

export default About