import React from 'react'
import { Container } from 'react-bootstrap'

const CGV = () => {
  return (
    <>
        <Container style ={{marginTop:'50px'}}>
            <h1>Condition Général de Ventes</h1>
            <h6>Definitions</h6>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro error officia officiis doloremque odio beatae quibusdam. At porro perspiciatis ipsum atque temporibus dolores consequuntur harum excepturi ducimus quos tempore iure enim aperiam officia id alias quas asperiores soluta aspernatur, sint itaque quam quisquam incidunt a! Odit sed eos iste. Ex, facilis impedit? Ratione, inventore! Ipsum deleniti odit quo doloremque cupiditate aliquid debitis reprehenderit fuga pariatur sed quaerat esse nostrum laborum aliquam ullam id aperiam, quam optio facilis aut eligendi dolor! Laborum, animi ipsum autem molestias ullam quibusdam omnis ipsa recusandae aut dolorem officia, ratione quaerat, voluptate tempore eveniet placeat optio expedita ab exercitationem. Laboriosam iure quaerat omnis, distinctio odit saepe nostrum, error nemo, consequatur molestias illo. Quidem labore ex at odio quis? Harum laborum nam corrupti suscipit architecto exercitationem dolor repudiandae a soluta, libero assumenda officia possimus earum voluptates mollitia voluptas aliquam est rem porro voluptatum esse magni modi vero pariatur. Neque ducimus quaerat reiciendis voluptates. Natus maiores repellendus, delectus reprehenderit, sit sequi sint perferendis assumenda quis reiciendis error quidem saepe non voluptates exercitationem culpa! Animi aliquam tenetur, veritatis sapiente deleniti voluptatum harum ex. Excepturi, aperiam. Aspernatur, optio non! Officiis expedita ducimus quia non rerum reiciendis aspernatur, quo quibusdam eum!</p>
            <h6>PORTRE DES ConDition generAles DE Vente</h6>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo quo rerum voluptatibus nulla consequatur quaerat sit, temporibus ut magnam blanditiis! Odit temporibus labore quibusdam, pariatur maiores doloribus. Iure nostrum reiciendis ratione dicta qui eos alias, reprehenderit repudiandae in, voluptas ullam hic nemo ducimus? Suscipit ipsam possimus fuga non illum alias, aut adipisci dolorum cupiditate error praesentium quibusdam sapiente exercitationem temporibus. Labore corporis est aut at quas, maiores fugit soluta voluptas accusantium. Nam quis perferendis recusandae optio. Quisquam iste distinctio nulla quo ipsam, iure nobis! Autem enim, quasi, quam quisquam in, pariatur maiores culpa adipisci repellendus eligendi sit eaque vero labore voluptate! Iusto excepturi deserunt vitae aliquid laborum ut repudiandae tempore sed amet dolorum corrupti sit fugiat nulla quisquam, modi quo quae rerum expedita, reprehenderit doloremque? Molestias animi ab quas nam nisi, laboriosam, ut consequuntur, qui officia earum at reiciendis sapiente fugit illo. Nostrum, omnis quis modi est qui nisi? Eius alias nostrum consequuntur eveniet dolorum voluptatem sint, natus nam sapiente fugit! Eveniet, sint nulla? Ipsa sequi doloremque facilis, ea cupiditate omnis ipsam. Labore quasi placeat deleniti eum vero explicabo rem itaque obcaecati nam omnis eligendi consequuntur illo id corporis voluptas, voluptatem quo qui quas voluptates? Vel rerum voluptatum qui commodi facere. Deserunt et tempore sit magnam nulla dolorum numquam ducimus ipsum eveniet laboriosam fugiat ea ad hic quaerat, soluta omnis voluptatem incidunt laborum dolorem doloremque magni esse! Soluta cupiditate officiis obcaecati autem sapiente natus necessitatibus aspernatur, neque illo repellendus atque non velit rerum voluptatem, nesciunt asperiores. Earum nisi odit fugit adipisci veniam accusantium cum pariatur. Mollitia ad architecto minus aliquam fuga voluptate libero minima inventore maiores totam possimus, odio vel soluta eos id aliquid nobis, veniam tenetur obcaecati. Assumenda omnis eveniet esse rerum saepe facere ipsum nemo, distinctio porro nesciunt repellat quae maxime odio corporis optio. Commodi ducimus hic eos!</p>
            <h6>ACCEPTATION DES CGV</h6>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Assumenda excepturi repellat reprehenderit fuga a pariatur quo accusamus harum exercitationem possimus dolorum beatae libero nisi aut dolore illo tenetur corporis, minima aliquid unde mollitia laborum corrupti. Quaerat quam nobis ullam voluptate.</p>
            <h6>TERITOIRE-ZONES DE LIVRAISON</h6>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis explicabo natus eum amet delectus! Iure, laudantium. Qui corrupti doloremque iure corporis, quo perferendis rerum fugiat optio cum neque consectetur molestiae ipsa placeat autem eum, asperiores a, reprehenderit culpa veritatis. Architecto, voluptatum reprehenderit. Magnam ut placeat quisquam molestiae cumque, porro libero quasi atque unde, esse asperiores quas ducimus, doloremque doloribus culpa. Recusandae temporibus perferendis atque pariatur mollitia fugiat, tenetur delectus natus, ipsa rem modi blanditiis illo minus commodi quam soluta nisi.</p>
        </Container>
    </>
  )
}

export default CGV